"""Configuration management — YAML loading, profiles, env vars, validation."""

from __future__ import annotations

import os
from copy import deepcopy
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from auth_scan.core.exceptions import ConfigError

DEFAULT_CONFIG_YAML = """\
# auth-scan configuration file
# Generated by: auth-scan --init

# Override the CLI target (useful for config-driven scans)
target: ""

# === Module Configuration ===
modules:
  - probe
  - jwt
  - session
  - brute

# === HTTP Configuration ===
rate_limit: 10
timeout: 30
user_agent: "auth-scan/0.1.0"
proxy: ""
headers: {}
cookies: {}

# === Authentication Configuration ===
auth:
  type: ""
  credentials: {}

# === Scope Configuration ===
scope:
  allow: []
  deny: []

# === Output Configuration ===
output:
  formats:
    - terminal
  directory: "./scan-results"
  no_redact: false

# === Wordlist Configuration ===
wordlists:
  passwords: ""
  usernames: ""

# === Agentic Engine Configuration ===
agentic:
  enabled: false
  max_depth: 5
  confidence_threshold: 0.9

# === Profiles ===
# Named sets of overrides. Use with: auth-scan --profile <name>
profiles:
  quick-owa:
    modules: [probe]
    agentic:
      enabled: false

  deep-jwt:
    modules: [probe, jwt, session]
    rate_limit: 5
    agentic:
      enabled: true
      max_depth: 8

  ci-pipeline:
    modules: [probe, jwt, session]
    output:
      formats: [json, sarif]
    agentic:
      enabled: false

  full-pentest:
    rate_limit: 3
    timeout: 60
    agentic:
      enabled: true
      max_depth: 10
      confidence_threshold: 0.95
"""


@dataclass
class ScanConfig:
    """Complete scan configuration with all parameters."""

    # Target
    target: str = ""

    # Modules
    modules: list[str] = field(default_factory=lambda: ["probe", "jwt", "session", "brute"])
    quick: bool = False

    # HTTP
    rate_limit: int = 10
    timeout: int = 30
    user_agent: str = ""  # empty -> HTTPClient injects f"auth-scan/{__version__}"
    proxy: str = ""
    headers: dict[str, str] = field(default_factory=dict)
    cookies: dict[str, str] = field(default_factory=dict)
    no_verify: bool = False
    ca_bundle: str = ""
    # When True, the probe falls back from HTTPS to plain HTTP if HTTPS
    # fails (legacy auth-scan behaviour). Off by default so credentials
    # never silently travel in plaintext. See PR-3 / H4.
    allow_http_fallback: bool = False

    # Authentication
    auth_type: str = ""  # bearer, basic, form, cookie
    auth_credentials: dict[str, str] = field(default_factory=dict)

    # Scope
    scope_allow: list[str] = field(default_factory=list)
    scope_deny: list[str] = field(default_factory=list)

    # Output
    output_formats: list[str] = field(default_factory=lambda: ["terminal"])
    output_dir: str = "./scan-results"
    no_redact: bool = False
    no_color: bool = False
    verbose: int = 0
    quiet: bool = False

    # Wordlists
    wordlist: str = ""
    user_wordlist: str = ""
    jwt_wordlist: str = ""
    # Override path for the bundled default-credentials wordlist used by
    # BruteForce. Empty = use the bundled list. M3.
    default_creds_path: str = ""

    # Phase-2 module toggles
    no_discovery: bool = False
    no_mfa: bool = False

    # OAuth scope-escalation value (plain text, requests will URL-encode)
    oauth_scope: str = "admin profile email openid"

    # Single-file output (companion to output_formats); empty means use output_dir
    output_file: str = ""

    # Agentic
    agentic: bool = False
    max_depth: int = 5
    confidence_threshold: float = 0.9

    # Resume
    resume_scan_id: str = ""

    # Config file path (for reference)
    config_path: str = ""

    def validate(self) -> None:
        """Validate configuration values, raising ConfigError on issues."""
        if self.rate_limit < 1:
            raise ConfigError(f"rate_limit must be >= 1, got {self.rate_limit}")
        if self.rate_limit > 100:
            raise ConfigError(f"rate_limit must be <= 100, got {self.rate_limit}")
        if self.timeout < 1:
            raise ConfigError(f"timeout must be >= 1, got {self.timeout}")
        if self.max_depth < 1:
            raise ConfigError(f"max_depth must be >= 1, got {self.max_depth}")
        if not 0.0 <= self.confidence_threshold <= 1.0:
            raise ConfigError(
                f"confidence_threshold must be between 0.0 and 1.0, got {self.confidence_threshold}"
            )
        valid_auth_types = {"", "bearer", "basic", "form", "cookie"}
        if self.auth_type not in valid_auth_types:
            raise ConfigError(f"auth_type must be one of {valid_auth_types}, got '{self.auth_type}'")
        valid_formats = {"terminal", "json", "markdown", "html", "pdf", "sarif"}
        for fmt in self.output_formats:
            if fmt not in valid_formats:
                raise ConfigError(f"output format must be one of {valid_formats}, got '{fmt}'")

    def merge_cli_overrides(self, **kwargs: Any) -> ScanConfig:
        """Merge CLI flag overrides into the config."""
        for key, value in kwargs.items():
            if value is not None and hasattr(self, key):
                current = getattr(self, key)
                # Only override if the value is different from the default
                # and was explicitly provided
                if isinstance(current, bool):
                    if value:  # Only override if truthy for bools
                        setattr(self, key, value)
                elif isinstance(current, list) and isinstance(value, (list, tuple)):
                    if value:
                        setattr(self, key, list(value))
                elif value:
                    setattr(self, key, value)
        return self


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Deep merge two dicts. override values take precedence."""
    result = deepcopy(base)
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = deepcopy(value)
    return result


def _apply_env_overrides(config_dict: dict[str, Any]) -> dict[str, Any]:
    """Apply AUTH_SCAN_* environment variable overrides."""
    env_prefix = "AUTH_SCAN_"
    for env_key, env_val in os.environ.items():
        if not env_key.startswith(env_prefix):
            continue
        # Convert AUTH_SCAN_RATE_LIMIT -> rate_limit
        key_path = env_key[len(env_prefix) :].lower().split("__")

        # Type coercion
        typed_val: Any = env_val
        if env_val.lower() in ("true", "yes", "1"):
            typed_val = True
        elif env_val.lower() in ("false", "no", "0"):
            typed_val = False
        elif env_val.isdigit():
            typed_val = int(env_val)
        elif env_val.replace(".", "", 1).isdigit():
            typed_val = float(env_val)
        elif env_val.startswith("[") and env_val.endswith("]"):
            import json

            try:
                typed_val = json.loads(env_val)
            except json.JSONDecodeError:
                pass

        # Navigate nested dict
        d = config_dict
        for part in key_path[:-1]:
            if part not in d:
                d[part] = {}
            d = d[part]
        d[key_path[-1]] = typed_val

    return config_dict


def load_config(
    config_path: str | None = None,
    profile: str | None = None,
    cli_overrides: dict[str, Any] | None = None,
) -> ScanConfig:
    """Load configuration from YAML file, profile, env vars, and CLI overrides.

    Precedence (highest to lowest):
    1. CLI overrides (--set and explicit flags)
    2. Environment variables (AUTH_SCAN_*)
    3. Named profile (--profile)
    4. Config file values
    5. Defaults
    """
    config_dict: dict[str, Any] = {}

    # Load from file
    if config_path:
        path = Path(config_path)
        if not path.exists():
            raise ConfigError(f"Config file not found: {config_path}")
        with open(path) as f:
            config_dict = yaml.safe_load(f) or {}

    # Extract profiles section before merging
    profiles = config_dict.pop("profiles", {})

    # Apply profile overrides
    if profile:
        if profile not in profiles:
            available = ", ".join(profiles.keys()) or "none"
            raise ConfigError(f"Profile '{profile}' not found. Available profiles: {available}")
        config_dict = _deep_merge(config_dict, profiles[profile])
        config_dict.pop("profiles", None)

    # Apply environment variable overrides
    config_dict = _apply_env_overrides(config_dict)

    # Build ScanConfig from dict
    config = _dict_to_config(config_dict)

    # Apply CLI overrides
    if cli_overrides:
        config.merge_cli_overrides(**cli_overrides)

    # Set config path for reference
    config.config_path = config_path or ""

    return config


def _dict_to_config(d: dict[str, Any]) -> ScanConfig:
    """Convert a nested config dict to a ScanConfig dataclass."""
    cfg = ScanConfig()

    # Top-level simple fields
    simple_fields = [
        "target",
        "rate_limit",
        "timeout",
        "user_agent",
        "proxy",
        "no_verify",
        "ca_bundle",
        "allow_http_fallback",
        "no_redact",
        "no_color",
        "verbose",
        "quiet",
        "wordlist",
        "user_wordlist",
        "jwt_wordlist",
        "default_creds_path",
        "agentic",
        "max_depth",
        "confidence_threshold",
        "resume_scan_id",
        "quick",
        "no_discovery",
        "no_mfa",
        "oauth_scope",
        "output_file",
    ]
    for field_name in simple_fields:
        if field_name in d:
            setattr(cfg, field_name, d[field_name])

    if "modules" in d:
        cfg.modules = d["modules"]

    if "headers" in d:
        cfg.headers = d["headers"]

    if "cookies" in d:
        cfg.cookies = d["cookies"]

    # Auth
    if "auth" in d:
        auth = d["auth"]
        if isinstance(auth, dict):
            cfg.auth_type = auth.get("type", "")
            cfg.auth_credentials = auth.get("credentials", {})

    # Scope
    if "scope" in d:
        scope = d["scope"]
        if isinstance(scope, dict):
            cfg.scope_allow = scope.get("allow", [])
            cfg.scope_deny = scope.get("deny", [])

    # Output
    if "output" in d:
        out = d["output"]
        if isinstance(out, dict):
            cfg.output_formats = out.get("formats", ["terminal"])
            cfg.output_dir = out.get("directory", "./scan-results")
            cfg.no_redact = out.get("no_redact", False)

    # Wordlists
    if "wordlists" in d:
        wl = d["wordlists"]
        if isinstance(wl, dict):
            cfg.wordlist = wl.get("passwords", "")
            cfg.user_wordlist = wl.get("usernames", "")

    # Agentic
    if "agentic" in d:
        ag = d["agentic"]
        if isinstance(ag, dict):
            cfg.agentic = ag.get("enabled", False)
            cfg.max_depth = ag.get("max_depth", 5)
            cfg.confidence_threshold = ag.get("confidence_threshold", 0.9)

    return cfg


def generate_default_config(path: str = "auth-scan-config.yml") -> str:
    """Write the default configuration file and return the path."""
    filepath = Path(path)
    filepath.write_text(DEFAULT_CONFIG_YAML)
    return str(filepath.resolve())
